version: "3"
services:
  firebird:
    container_name: "firebirdss"
    image: docker.pkg.github.com/joaodforce/docker-firebird/firebirdss:2.1
    restart: always
    expose:
      - 3050
    ports:
      - 3050:3050
    volumes:
      - /mnt/samba/Databases/:/firebird
    ulimits:
      nofile:
        soft: 65535
        hard: 100000
