version: "3"
services:
  firebird:
    build: .
    expose:
      - 3050
    ports:
      - 3050:3050
    volumes:
      - .:/firebird
    ulimits:
      nofile:
        soft: 65535
        hard: 100000
